name: test

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          access-key-id: ${{ secrets.AK }}
          access-key-secret: ${{ secrets.SK }}
          region-id: cn-hongkong
          container-group-name: pingpu
